/*
 * minotari
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountBalance {
    #[serde(
        rename = "max_date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_date: Option<Option<String>>,
    #[serde(
        rename = "max_height",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_height: Option<Option<i64>>,
    #[serde(
        rename = "total_credits",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_credits: Option<Option<i64>>,
    #[serde(
        rename = "total_debits",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_debits: Option<Option<i64>>,
}

impl AccountBalance {
    pub fn new() -> AccountBalance {
        AccountBalance {
            max_date: None,
            max_height: None,
            total_credits: None,
            total_debits: None,
        }
    }
}
