/*
 * minotari
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiErrorOneOf2 {
    #[serde(rename = "AccountNotFound")]
    pub account_not_found: String,
}

impl ApiErrorOneOf2 {
    pub fn new(account_not_found: String) -> ApiErrorOneOf2 {
        ApiErrorOneOf2 { account_not_found }
    }
}
