/*
 * minotari
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiErrorOneOf1 {
    #[serde(rename = "DbError")]
    pub db_error: String,
}

impl ApiErrorOneOf1 {
    pub fn new(db_error: String) -> ApiErrorOneOf1 {
        ApiErrorOneOf1 { db_error }
    }
}
