/*
 * minotari
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiErrorOneOf {
    #[serde(rename = "InternalServerError")]
    pub internal_server_error: String,
}

impl ApiErrorOneOf {
    pub fn new(internal_server_error: String) -> ApiErrorOneOf {
        ApiErrorOneOf { internal_server_error }
    }
}
