/*
 * minotari
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiError {
    ApiErrorOneOf(Box<models::ApiErrorOneOf>),
    ApiErrorOneOf1(Box<models::ApiErrorOneOf1>),
    ApiErrorOneOf2(Box<models::ApiErrorOneOf2>),
    ApiErrorOneOf3(Box<models::ApiErrorOneOf3>),
}

impl Default for ApiError {
    fn default() -> Self {
        Self::ApiErrorOneOf(Default::default())
    }
}
