/*
 * minotari
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTransactionRequest {
    #[serde(
        rename = "idempotency_key",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub idempotency_key: Option<Option<String>>,
    #[serde(
        rename = "payment_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub payment_id: Option<Option<String>>,
    #[serde(rename = "recipients")]
    pub recipients: Vec<models::RecipientRequest>,
    #[serde(
        rename = "seconds_to_lock_utxos",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub seconds_to_lock_utxos: Option<Option<i64>>,
}

impl CreateTransactionRequest {
    pub fn new(recipients: Vec<models::RecipientRequest>) -> CreateTransactionRequest {
        CreateTransactionRequest {
            idempotency_key: None,
            payment_id: None,
            recipients,
            seconds_to_lock_utxos: None,
        }
    }
}
