/*
 * minotari
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecipientRequest {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "amount")]
    pub amount: i64,
}

impl RecipientRequest {
    pub fn new(address: String, amount: i64) -> RecipientRequest {
        RecipientRequest { address, amount }
    }
}
